# Generated by Django 4.2 on 2024-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outletproducts",
            name="max_quantity",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="remainingproducts",
            name="max_quantity",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
