# Generated by Django 4.2 on 2024-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_outletproducts_max_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outletproducts",
            name="max_quantity",
            field=models.CharField(default="1", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="remainingproducts",
            name="max_quantity",
            field=models.CharField(default="1", max_length=20, null=True),
        ),
    ]
