# Generated by Django 4.2 on 2024-08-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_outlet_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("details", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
