# Generated by Django 4.2 on 2024-08-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlet", name="number", field=models.CharField(max_length=12),
        ),
    ]
