# Generated by Django 4.2 on 2024-12-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_outletproducts_max_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutletPending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outlet", models.CharField(max_length=50)),
                ("pending", models.CharField(max_length=50)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
