# Generated by Django 4.2 on 2024-12-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_outletpending"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="type",
            field=models.CharField(default="employee", max_length=50, null=True),
        ),
    ]
