# Generated by Django 4.2 on 2024-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_outlet_created_outlet_updated_product_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutletProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift", models.IntegerField()),
                ("image_url", models.CharField(max_length=255)),
                ("product_name", models.CharField(max_length=50)),
                ("product_price", models.CharField(max_length=50)),
                ("product_details", models.CharField(max_length=255)),
                ("outlet_name", models.CharField(max_length=50)),
                ("outlet_location", models.CharField(max_length=50)),
                ("outlet_number", models.CharField(max_length=12)),
                ("outlet_store_id", models.CharField(max_length=20)),
                ("cash_in_hand", models.CharField(max_length=20)),
                ("outstanding_balance", models.CharField(max_length=20)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
