# Generated by Django 4.2 on 2025-02-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_users_profile_url_users_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="emp_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="mobile",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
