# Generated by Django 4.2 on 2024-09-04 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_saleproducts_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="users",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
