# Generated by Django 4.2 on 2025-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_users_emp_id_users_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
