# Generated by Django 4.2 on 2025-02-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_users_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="outletpending",
            name="emp_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="outletproducts",
            name="emp_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="remainingproducts",
            name="emp_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="saleproducts",
            name="emp_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
